spring.application.name=rabbitmq-application

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_USER:guest}

server.port=8080